# -- Path setup --------------------------------------------------------------

import os
import sys

# Add the path to your Python code, so Sphinx can find and document your modules.
# This assumes your Python files are located in the parent directory.
sys.path.insert(0, os.path.abspath(r'C:\Users\nsucc\Desktop\python env\lab3'))


# -- Project information -----------------------------------------------------

project = 'School Management System'
author = 'Nadim'
release = '1.0'  # The version of your project

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings.
# These are commonly used extensions for generating documentation from Python code.
extensions = [
    'sphinx.ext.autodoc',      # Automatically document your code
    'sphinx.ext.viewcode',     # Add links to the source code
    'sphinx.ext.napoleon'      # Support for Google-style and NumPy-style docstrings
]

# The templates path for customizing the HTML output.
templates_path = ['_templates']

# Patterns to exclude when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages. You can choose other themes.
# For example: 'alabaster', 'classic', 'nature', etc.
html_theme = 'sphinx_rtd_theme'  # Read The Docs theme (clean and responsive)

# Add paths that contain custom static files (such as style sheets).
# These files are copied after the built-in static files, so a file named "default.css"
# will overwrite the built-in "default.css".
html_static_path = ['_static']

# -- Autodoc configuration ---------------------------------------------------

# This setting ensures that Sphinx generates documentation even if your docstrings
# are missing or incomplete.
autodoc_default_options = {
    'members': True,           # Include class members (functions and attributes)
    'undoc-members': True,     # Include undocumented members
    'private-members': True,   # Include private members (starting with _)
    'special-members': True,   # Include special members (e.g., __init__)
    'inherited-members': True, # Include inherited members from parent classes
    'show-inheritance': True   # Show class inheritance
}

# Include the index and any other .rst files generated by `sphinx-apidoc`
# or written by you in `index.rst`.
master_doc = 'index'  # The main .rst file that acts as the entry point

# Enable showing the code along with the documentation (via viewcode).
html_show_sourcelink = True

# -- Napoleon settings -------------------------------------------------------

# Configuring Napoleon to parse both Google-style and NumPy-style docstrings.
napoleon_google_docstring = True
napoleon_numpy_docstring = True

